# Month to num mapping with all variations
FRENCH_MONTHS = {
        "janvier": 1,
        "janv": 1,
        "février": 2,
        "fevrier": 2,
        "fev": 2,
        "fév": 2,
        "mars": 3,
        "avril": 4,
        "avr": 4,
        "mai": 5,
        "juin": 6,
        "juillet": 7,
        "août": 8,
        "aout": 8,
        "septembre": 9,
        "octobre": 10,
        "novembre": 11,
        "décembre": 12,
        "decembre": 12,
    }