apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow

metadata:
  name: weekly-job

spec:
  schedule: "0 8 * * 1"

  timezone: UTC

  workflowSpec:

    entrypoint: execute

    templates:

      - name: execute

        container:

          image: ghcr.io/my-org/my-app:1.0

          command:
            - python

          args:
            - src/main.py